# Define the Docker image to use for the workspace
image:
  file: .github/.gitpod.Dockerfile

# Define tasks that will run when the workspace is initialized
tasks:
  - before: echo "Initializing Gitpod for Nextflow course..."

  - init: install vscode dependency
    command: |
      gp install *.vsix

  - name: Test dependencies
    command: |
      # Activate the conda environment for Nextflow
      source /opt/conda/bin/activate nextflow_course
      # Verify that Nextflow and other tools are installed correctly
      nextflow -version
      nf-core --version
      pytest --version
      # Display course title:
      cat assets/course_title_ASCIII.txt
      # Validate environment
      echo "Environment is ready!"
  - name: Access to practical lessons directory
    command: cd /workspace/course-nextflow-bioinformatics/course_content/hands_on

vscode:
    extensions:
        - codezombiech.gitignore # Language support for .gitignore files
        - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
        - EditorConfig.EditorConfig # Override user/workspace settings with settings found in .editorconfig files
        - Gruntfuggly.todo-tree # Display TODO and FIXME in a tree view in the activity bar
        - nextflow.nextflow # Nextflow syntax highlighting
        - streetsidesoftware.code-spell-checker # Spelling checker for source code
        - ms-python.python # Python support
        - redhat.vscode-yaml # YAML support
        - ms-toolsai.jupyter # Jupyter Notebooks support
